name: test
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: ['ubuntu-18.04', 'macOS-10.14', 'windows-2019']
        os: ['ubuntu-18.04']
        perl:
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm -n Devel::Cover::Report::Coveralls
      - run: cpanm --installdeps -n .
      - run: perl Build.PL && ./Build build && cover -test -report coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
